baseURL: https://grahame.com/
title: Grahame
languageCode: en-us
timeZone: America/New_York

disableKinds: [RSS, taxonomy]

# Custom output formats for resume
outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
    - resumeHTML

outputFormats:
  resumeHTML:
    name: Resume HTML
    mediaType: text/html
    baseName: grahame_murray_resume
    isPlainText: false
    permalinkable: true
    notAlternative: false

params:
  author: Grahame Murray

  description: |

    Raleighite husband

    Agnostic father

    Distinguished engineer

    Cat owning dog lover

    Pescatarian traveler

    Anglophile liberal

    Musical motorcyclist

    Sarcastic brewer

    Francophone roboticist

    Outdoorsy polymath

    Delawarean ISFJ

    Goofy night owl

    Curious runner

  social:
    github: gusnuf
    linkedin: grahamemurray
    soundcloud: gusnuf
    bsky: grahame.com
    substack: grahamemurray
    email: jobs@grahame.com

menu:
  main:
    - url: /
      name: Home
      weight: 1

    - url: /resume/
      name: Resume
      weight: 2
